---
# Install spark binaries

- name: download binaries
  get_url: >
    url={{ spark_url }}
    dest=/tmp/

- name: Install spark
  unarchive: >
    copy=no
    dest={{ install_dir}}
    src=/tmp/{{ spark_release }}
    owner={{ spark_user }}
    group={{ spark_user }}
    mode=755

- name: Create /opt/spark link
  file: >
    src={{ install_dir }}/spark-{{ spark_version }}-bin-hadoop{{ hadoop_version }}
    dest={{ spark_home }}
    state=link
    owner={{ spark_user }}
    group={{ spark_user }}
    mode=755

- name: Setup SPARK_HOME
  lineinfile: >
    dest=/etc/environment
    line='SPARK_HOME={{ spark_home }}'
