---
# Configure spark as a service

- name: Setup spark-master service
  template: >
    src=templates/spark
    dest=/etc/init.d/spark
    owner=root
    group=root
    mode=755
  when: inventory_hostname == 'spark-master'

- name: Setup service
  service: name=spark enabled=yes
  notify: start-spark
  when: inventory_hostname == 'spark-master'

